# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest tox briefcase
    - name: Test with tox
      run: |
        tox
    - name: Briefcase create
      run: |
        briefcase create
    - name: Briefcase build
      run: |
        briefcase build
    - name: Briefcase package
      run: |
        briefcase package
    - name: Upload exe
      uses: actions/upload-artifact@v3
      with:
        name: cityjson2ifc-${{ matrix.exe_os }}
        path: dist/*
        retention-days: 1